close all;
clear;
clc;
flicker_frequency=100;
generic_LIVI_simulation_direct();

close all;
clear;
clc;
flicker_frequency=90;
generic_LIVI_simulation_direct();

close all;
clear;
clc;
flicker_frequency=80;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=70;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=60;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=50;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=40;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=30;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=20;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=10;
generic_LIVI_simulation_direct();
close all;
clear;
clc;
flicker_frequency=1;
generic_LIVI_simulation_direct();


